### ISSUE TITLE
Typo error in book. ISBN 978-3-89576-618-3.

### ISSUE THREAD

**Issue by EmmanuelDiscors** [koenvervloesem/openthread-applications#1]
Hello Koen,
In the French edition of the book Building W.S.N. with OpenThread (ISBN 978-3-89576-618-3) there is a typo on page 99; third line:
I think it should read "CMakeLists.txt" rather than "CMakeLists.tst".
If this can help for the next edition, I will be happy.
Thank you again for this superb work.

**Comment by koenvervloesem** [comment]
Thanks for the correction, Emmanuel! I've [added](https://github.com/koenvervloesem/openthread-applications/commit/ac268b16cbe792bd1098818ccd4b1652d0e1d07c) it to the errata.
